[package]
name = "SovietWM"
version = "0.1.0"
edition = "2021"
author = "TheHolyTachanka"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
penrose = "0.2"
simplelog = "0.12.0"
toml = "0.5"
serde = "1.0.136"
serde_derive = "1.0.136"

